#!/usr/bin/env ruby
# frozen_string_literal: true

# NOTE: to suppress "Using the last argument as keyword parameters is deprecated" warning in tty-command
Warning[:deprecated] = false

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require 'blocky/cli'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Blocky::CLI.start
rescue Blocky::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
